# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 18:42
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Here', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
