# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 14:11
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Here', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
