# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Here', '0004_auto_20190417_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', tinymce.models.HTMLField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
