# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 17:59
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Here', '0006_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=tinymce.models.HTMLField(),
        ),
    ]
